<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_islandora_required_objects().
 */
function collation_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'collation');
  $create_object = function(array $args) use ($connection){
    $object = $connection->repository->constructObject($args['pid']);
    $object->owner = 'fedoraAdmin';
    $object->label = $args['label'];
    $object->models = $args['model'];
    foreach($args['datastreams'] as $dsid => $datastream) {
      $label = isset($datastream['label']) ? $datastream['label'] : 'M';
      $datastream = $object->constructDatastream($dsid, $label);
      $datastream->label = isset($datastream['label']) ? $datastream['label'] : $dsid;
      $datastream->mimetype = isset($datastream['mimetype']) ? $datastream['mimetype'] : 'text/xml';
      $datastream->setContentFromFile($datastream['file'], FALSE);
      $object->ingestDatastream($datastream);
    }
    return $object;
  };
  // Critical Edition Content Model.
  $collation_content_model = $create_object(array(
    'pid' => 'islandora:collationCModel',
    'label' => 'Collation Content Model',
    'model' => 'fedora-system:ContentModel-3.0',
    'datastreams' => array(
      'DS-COMPOSITE-MODEL' => array(
        'file' => "$module_path/data/objects/collation_ds_composite_model.xml",
      ),
    ),
  ));
  return array(
    'collation' => array(
      'title' => 'EMiC (Editing Modernism in Canada) - Collations',
      'objects' => array(
        $collation_content_model,
      ),
    ),
  );
}