<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

function versionable_object_viewer_menu() {

  $items = array();
  $items['islandora/object/%islandora_object/get_tree_data'] = array(
    'title' => 'Prepare advanced viewer',
    'page callback' => 'versionable_object_viewer_build_tree',
    'file' => 'includes/utilities.inc',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
    'access callback' => 'user_access',
    'access arguments' => array(TRUE),
  );
  $items['islandora/object/%islandora_object/get_transcription_data'] = array(
    'title' => 'Prepare transcription data',
    'page callback' => 'versionable_object_viewer_build_transcription_data',
    'file' => 'includes/utilities.inc',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
    'access callback' => 'user_access',
    'access arguments' => array(TRUE),
  );
  $items['islandora/cwrc_viewer/detail_meta_data'] = array(
    'title' => 'Prepare Metadata view',
    'page callback' => 'versionable_object_viewer_prepare_detail_meta_data',
    'type' => MENU_CALLBACK,
    'file' => 'includes/utilities.inc',
    'access callback' => 'user_access',
    'access arguments' => array(TRUE),
  );
  $items['islandora/version_viewer/tei_markup/page/%islandora_object'] = array(
    'title' => 'Prepare Page consolidated TEI',
    'page callback' => 'versionable_object_viewer_prepare_page_tei_consolidated',
    'file' => 'includes/utilities.inc',
    'page arguments' => array(4),
    'type' => MENU_CALLBACK,
    'access callback' => 'user_access',
    'access arguments' => array(TRUE),
  );
//   $items['islandora/version_viewer/tei_markup/page/%islandora_object'] = array(
//     'title' => 'Prepare Page TEI Markup',
//     'page callback' => 'versionable_object_viewer_display_page_tei',
//     'page arguments' => array(3),
//     'type' => MENU_CALLBACK,
//     'access callback' => 'user_access',
//     'access arguments' => array(ISLANDORA_CRITICAL_EDITION_ADVANCED_READ),
//   );
//   $items['islandora/cwrc_viewer/detail_meta_data'] = array(
//     'title' => 'Prepare Metadata view',
//     'page callback' => 'islandora_critical_edition_advanced_prepare_detail_meta_data',
//     'type' => MENU_CALLBACK,
//     'access callback' => 'user_access',
//     'access arguments' => array(ISLANDORA_CRITICAL_EDITION_ADVANCED_READ),
//   );
//   $items['islandora/cwrc_viewer/detail_transcription'] = array(
//     'title' => 'Prepare Metadata view',
//     'page callback' => 'islandora_critical_edition_advanced_prepare_detail_transcription',
//     'type' => MENU_CALLBACK,
//     'access callback' => 'user_access',
//     'access arguments' => array(ISLANDORA_CRITICAL_EDITION_ADVANCED_READ),
//   );
//   $items['islandora/cwrc_viewer/transformed_page/%islandora_object'] = array(
//     'title' => 'Prepare Page consolidated TEI',
//     'page callback' => 'islandora_critical_edition_advanced_prepare_page_tei_consolidated',
//     'page arguments' => array(3),
//     'type' => MENU_CALLBACK,
//     'access callback' => 'user_access',
//     'access arguments' => array(ISLANDORA_CRITICAL_EDITION_ADVANCED_READ),
//   );
  return $items;
}

/**
 * Implements hook_theme().
 */
function versionable_object_viewer_theme($existing, $type, $theme, $path) {
  return array(
    'versionable_object_viewer' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/versionable_object_viewer',
      'variables' => array(
        'islandora_object' => NULL,
        'anno_img_pane' => NULL,
        'version_data' => NULL,
        'tree_source' => NULL,
        'transcription_source' => NULL,
        'meta_source' => NULL,
        'islandora_content' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_library().
 */
function versionable_object_viewer_library() {
  $module_path = drupal_get_path('module', 'versionable_object_viewer');
  $items = array();

  $items['jq_uilayout'] = array(
    'title' => t('jQuery UILayout'),
    'version' => '1.0',
    'js' => array(
      "$module_path/js/jquery/jquery.layout-latest.min.js" => array(),
      "$module_path/js/jquery/jquery.ui.all.js" => array(),
    ),
    'css' => array(
      "$module_path/js/jquery/layout-default-latest.css" => array(),
    ),
  );

  $items['jq_latest'] = array(
    'title' => t('jQuery'),
    'version' => '1.11.1',
    'js' => array(
      "$module_path/js/jquery/jquery-1.11.1.min.js" => array(),
    ),
    'css' => array(
      "$module_path/js/jquery/layout-default-latest.css" => array(),
    ),
  );

  $items['jquery_easy_ui'] = array(
    'title' => t('jQuery EasyUI'),
    'version' => '1.3.6',
    'js' => array(
      "$module_path/js/jquery/jquery-easyui/jquery.min.js" => array(),
      "$module_path/js/jquery/jquery-easyui/jquery.easyui.min.js" => array(),
    ),
    'css' => array(
      "$module_path/js/jquery/jquery-easyui/themes/default/easyui.css" => array(),
      "$module_path/js/jquery/jquery-easyui/themes/icon.css" => array(),
      //"$module_path/js/jquery/jquery-easyui/demo/demo.css" => array(),
    ),
  );

  return $items;
}

/**
 * Implements hook_CMODEL_islandora_view_object().
 */
function versionable_object_viewer_islandora_versionCModel_islandora_view_object(AbstractObject $object) {
  $module_path = drupal_get_path('module', 'versionable_object_viewer');
  module_load_include('inc', 'islandora_image_annotation', 'includes/callbacks');

  // Add the jQuery EasyUI library.
  drupal_add_library('versionable_object_viewer', 'jquery_easy_ui');
  drupal_add_js("$module_path/js/init.js");

  $transcriptions = versionable_object_viewer_get_transcription_text($object);

  // Theme our verionable object viewer.
  return theme('versionable_object_viewer',
    array(
      'islandora_object' => $object,
      'version_data' => $transcriptions
    )
  );
}

function versionable_object_viewer_preprocess_versionable_object_viewer(&$variables) {
  module_load_include('inc', 'islandora_image_annotation', 'includes/utils');
  module_load_include('inc', 'versionable_object_viewer', 'includes/utilities');
  module_load_include('inc', 'php_lib', 'DOMHelpers');
  $module_path = drupal_get_path('module', 'versionable_object_viewer');

  dom_document_pretty_print_include_files();

  $version_object = $variables['islandora_object'];
  drupal_add_css("$module_path/css/islandora_critical_edition_diplomatic_tei.css");
  drupal_add_css("$module_path/css/islandora_critical_edition_reading_tei.css");


  $source = versionable_object_viewer_process_version_object_source($version_object);
  $source_object = islandora_object_load($source[0]['obj']['value']);

  $variables['version_source'] = $source;
  $variables['content_model'] = str_replace("info:fedora/", "", $source[0]['type']['uri']);
  $variables['transcription_source'] = url("islandora/object/$version_object->id/get_transcription_data");
  $variables['meta_source'] = url("islandora/cwrc_viewer/detail_meta_data");


  drupal_add_js(array('versionable_object_viewer' => array('trans_url' => $variables['transcription_source'])), 'setting');


  versionable_object_viewer_build_version_media_view($source_object, $variables);
}

function versionable_object_viewer_get_transcription_text($object) {
  module_load_include('inc', 'versionable_object_viewer', 'includes/utilities');

  // Gather all transcriptions for this versionable object.
  $transcriptions_data = versionable_object_viewer_get_related_transcriptions($object->id);
  $transcriptions = array();
  foreach ($transcriptions_data as $key => $value) {
    $trans = islandora_object_load($key);
    $transcription_details['title'] = $transcriptions_data[$key];
    $transcription_details['text'] = $trans['TRANSCRIPTION']->content;
    array_push($transcriptions, $transcription_details);
  }
  return $transcriptions;
}
